volumes:
  db-data:

services:
  server:
    build:
      context: .
      target: final
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=SafeShare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # only for local development
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  swagger-local:
    image: docker.swagger.io/swaggerapi/swagger-ui
    ports:
      - "4000:8080"
    environment:
      - SWAGGER_JSON_URL=http://localhost:8080/api/v1/docs/swagger.json

  swagger-docker:
    image: docker.swagger.io/swaggerapi/swagger-ui
    ports:
      - "4001:8080"
    environment:
      - SWAGGER_JSON_URL=http://localhost:8081/api/v1/docs/swagger.json
