### common settings
app_name: "SafeShare"
debug: true
development: true
server:
  port: 8080

### logging
logging:
  console:
    enabled: true
    level: debug
  file:
    enabled: true
    level: debug

### database
database:
  url: "postgresql://postgres:postgres@localhost:5432/SafeShare"